### ISSUE TITLE
[Tracking] Graphics

### ISSUE THREAD

**Issue by senden9** [senden9/StarSystemExplorer#12]
Tracking issue for our artist because she have no GitHub account.
Search or create the following graphics

Must have:
- [x] Starship
- [x] Planets
  - [x] Different spirits depending on the resources available
  - [x] Different spirits depending on the colonisation
- [x] Background
- [ ] Landing capsules
- [x] Asteroids

Nice to have:
- [ ] Fog to hide

**Comment by senden9** [comment]
Add some temporary planet resources. To use until the _real_ resources are here. See 817b5bab26191f2a6260ffeeb591b96e6171d4dc
